// src/views/Add.vue
<template>
    <div class='grid justify-center'>
        <div class=' mt-4 grid justify-center items-center  rounded-lg bg-gray-100 mx-8 md:w-[640px] md:mx-32'>
            <div class='  justify-center items-center '>
                <div
                    class=' md:w-[640px]  px-6  py-3 border border-gray-400 bg-gray-200  text-left font-bold text-gray-800 rounded-t-md'>
                    <p>Add Contact</p>
                </div>
    
                <form action="" class='w-[400px] md:w-[640px]  text-left  px-4  pt-4' @submit="onSubmit">
                    <div class='flex flex-col justify-center space-y-2 '>
                        <label class='text-gray-700'>Name</label>
                        <input type="text" class=" border  pl-4 py-3 rounded-md" placeholder='Enter your name...'
                        v-model="name"
                            
                        />
                    </div>
                    <div class='flex flex-col justify-center space-y-2 mt-4'>
                        <label class='text-gray-700'>Email</label>
                        <input type="text" class=" border  pl-4 py-3 rounded-md" placeholder='Enter your email...'
                        v-model="email"
                        />
                    </div>
                    <div class='flex flex-col justify-center space-y-2 mt-4'>
                        <label class='text-gray-700'>phone</label>
                        <input type="text" class=" border  pl-4 py-3 rounded-md" placeholder='Enter your phone...'
                        v-model="phone"
                        />
                    </div>
    
                    <button class='bg-gray-800 text-center w-full text-gray-50 py-2 rounded-md my-4'>Submit</button>
    
    
                </form>
            </div>
    
        </div>
    
    </div>
</template>

<script>
export default {
    name: 'AddTask',
    data() {
        return {
            name: '',
            email: '',
            phone: ''

        }
    },
    methods: {
        onSubmit(e) {
            e.preventDefault()

            const newTask = {
                id: Math.floor(Math.random() * 100000),
                name: this.name,
                email: this.email,
                phone: this.phone
            }
            this.$emit('add-task',newTask)

            this.name = ""
            this.email = ""
            this.phone = ""

        }
    }
}
</script>

// Abdulramon Lasisi/Module 3/Task_1_React_Contact_App/contact-manager/src/components/Add.jsx
import React from 'react'
import { Link } from 'react-router-dom'
import { useGlobalContext } from '../context'

const Add = () => {
  const { newUser, handleChange, handleSubmit, isEdit, editUser, setIsEdit } =
    useGlobalContext()

  const { name, email, phone } = editUser

  return (
    <section className='border items-center rounded-md m-4 border-gray-300 overflow-hidden'>
      <div className='flex justify-between bg-gray-200 px-4 py-2'>
        <h2 className='text-lg font-bold p-1'>
          {isEdit ? 'Edit Contact' : 'Add Contact'}
        </h2>
        <button
          className='border px-3 text-xs cursor-pointer rounded-md shadow-sm border-gray-700 text-gray-700 hover:text-gray-100 hover:bg-gray-700 transition'
          onClick={() => setIsEdit(false)}
        >
          <Link to='/'>Back Home</Link>
        </button>
      </div>
      <hr className='bg-gray-300' />
      <form
        onSubmit={handleSubmit}
        className='bg-gray-50 px-4 py-2 space-y-6 pt-4'
      >
        <div className='flex flex-col gap-2'>
          <label htmlFor='name'>Name</label>
          <input
            type='text'
            id='name'
            name='name'
            placeholder='Enter your name...'
            value={isEdit ? name : newUser.name}
            onChange={handleChange}
            className='rounded-md px-4 py-2 border transition focus:outline-blue-200'
          />
        </div>

        <div className='flex flex-col gap-2'>
          <label htmlFor='email'>Email</label>
          <input
            type='email'
            id='email'
            name='email'
            placeholder='Enter your email...'
            value={isEdit ? email : newUser.email}
            onChange={handleChange}
            className='rounded-md px-4 py-2 border transition focus:outline-blue-200'
          />
        </div>

        <div className='flex flex-col gap-2'>
          <label htmlFor='phone'>Phone</label>
          <input
            type='tel'
            id='phone'
            name='phone'
            placeholder='Enter your phone...'
            value={isEdit ? phone : newUser.phone}
            onChange={handleChange}
            className='rounded-md px-4 py-2 border transition focus:outline-blue-200'
          />
        </div>

        <div className='flex bg-gray-600 rounded-md transition hover:bg-gray-800'>
          <button className='w-full py-2' type='submit'>
            {isEdit ? 'Update' : 'Submit'}
          </button>
        </div>
      </form>
    </section>
  )
}

export default Add
