// gamel.ayodele/Module-3/reactAss/src/component/Home.jsx
import React from "react";
import ContactList from "./ContactList";
import { useContext } from "react";
import InfoContext from "../context/InfoContext";

function Home({ onDelete }) {
  const { infos } = useContext(InfoContext);

  return (
    <div className="container">
      <div className=" main">
        <h2>Contact Manager</h2>
        <p>This is a portfolio project to showcase knowledge of:</p>
        <ol>
          <li>React Components and Jsx.</li>
          <li>React Router.</li>
          <li>Context api for global state management</li>
          <li>
            Making asynchronous calls to the json placeholder fake rest api
            using "async/await"
          </li>
        </ol>
      </div>

      {infos.map((info) => (
        <ContactList key={info.id} info={info} />
      ))}
    </div>
  );
}

export default Home;

// gamel.ayodele/Module-3/anglarAss/src/app/components/home/home.component.ts
import { Component, OnInit } from '@angular/core';
import { Observable, takeLast } from 'rxjs';
import { InfoService } from 'src/app/services/info.service';
import { Info } from '../../Info';

@Component({
  selector: 'app-home',
  templateUrl: './home.component.html',
  styleUrls: ['./home.component.css'],
})
export class HomeComponent implements OnInit {
  infos: Info[] = [];

  constructor(private infoService: InfoService) {}

  ngOnInit(): void {
    this.infoService.getInfo().subscribe((infos) => (this.infos = infos));
  }
  deleteInfo(info: Info) {
    this.infoService
      .deleteInfo(info)
      .subscribe(
        () => (this.infos = this.infos.filter((t) => t.id !== info.id))
      );
  }
  addInfo(info: Info) {
    this.infoService.addInfo(info).subscribe((info) => this.infos.push(info));
  }
}

<main>
  <div class="container">
    <div class="main">
      <h2>Contact Manager</h2>
      <p>This is a portfolio project to showcase knowledge of:</p>
      <ol>
        <li>Angular Component.</li>
        <li>Angular Router.</li>
        <li>
          Making asynchronous calls to the json placeholder fake rest api using
          "async/await"
        </li>
      </ol>
    </div>
    <!-- <app-add-info (onAddInfo)="addInfo($any($event))"></app-add-info> -->
    <app-info
      *ngFor="let info of infos"
      [info]="info"
      (OnDeleteInfo)="deleteInfo(info)"
    ></app-info>
  </div>
</main>
