// abdullahi.muritala/module 3/react-contact-man/src/components/Contacts.jsx
import React, { useContext } from 'react';
import { ContactContext } from '../App';
import Contact from './Contact';

const Contacts = () => {
  const { contactList } = useContext(ContactContext);
  return contactList.length
    ? contactList.map((contact) => (
        <Contact
          key={contact.id}
          id={contact.id}
          name={contact.name}
          email={contact.email}
          phone={contact.phone}
        />
      ))
    : '';
};

export default Contacts;

// abdullahi.muritala/module 3/vue-contact-man/src/components/Contacts.vue
<template>
  <div :key="contact.id" v-for="contact in allContacts">
    <Contact :contact="contact" />
  </div>
</template>

<script>
import { mapGetters } from 'vuex';
import Contact from '@/components/Contact.vue';

export default {
  name: 'Contacts',
  components: {
    Contact,
  },
  computed: mapGetters(['allContacts']),
};
</script>
