// toluwalase.adeosun/Module3/Vue_Task/vue-contact-manager/src/components/Hero.vue
<template>
  <div
    className="max-w-[1140px] m-auto bg-[#e9ecef] h-fit my-[1rem] rounded-md p-[2rem]"
  >
    <h1 className="text-center pt-[2rem] text-2xl font-bold">
      Contact Manager
    </h1>
    <p>This is a portfolio project to showcase knowledge of:</p>
    <ol className="list-[upper-roman] ml-[1rem]">
      <li>React Components and JSX.</li>
      <li>React Router.</li>
      <li>Component state management.</li>
      <li>Context api for global state management.</li>
      <li>
        Making asynchronous calls to the Json placeholder fake rest api using
        "async/await".
      </li>
    </ol>
  </div>
</template>

<script>
export default {
    name: 'Hero',
};
</script>

// toluwalase.adeosun/Module3/React_Task/contact-manager/src/components/Hero.jsx
import React from 'react';

const Hero = () => {
  return (
    <div className="max-w-[1140px] m-auto bg-[#e9ecef] h-fit my-[1rem] rounded-md p-[2rem]">
      <h1 className="text-center pt-[2rem] text-2xl font-bold">
        Contact Manager
      </h1>
      <p>This is a portfolio project to showcase knowledge of:</p>
      <ol className="list-[upper-roman] ml-[1rem]">
        <li> React Components and JSX.</li>
        <li> React Router.</li>
        <li>Component state management.</li>
        <li> Context api for global state management.</li>
        <li>
          Making asynchronous calls to the Json placeholder fake rest api using
          "async/await".
        </li>
      </ol>
    </div>
  );
};

export default Hero;
