// toluwalase.adeosun/Module3/React_Task/contact-manager/src/components/Add.jsx
import React from 'react';
import { useState } from 'react';

const Add = ({ addContact }) => {
  const [name, setName] = useState('');
  const [email, setEmail] = useState('');
  const [phoneNumber, setPhoneNumber] = useState('');

  const onSubmit = (e) => {
    e.preventDefault();

    if (!name || !phoneNumber || !email) {
      alert('Please add a task');
      return;
    }
    addContact({ name, phoneNumber, email });
    setName('');
    setEmail('');
    setPhoneNumber('');
  };
  return (
    <form className="max-w-[1140px] m-auto bg-[rgba(0,0,0,.03)] ">
      <h1 className="bg-[rgba(0,0,0,.03)] text-base font-bold border-[rgba(0,0,0,.125)] py-3 px-7 my-[2rem]">
        Add Contact
      </h1>
      <div className=" flex flex-col py-5 w-[95%] m-auto">
        <label className="mb-[0.5rem] text-base">Name</label>
        <input
          className="py-[0.75rem] px-[1rem] text-xl rounded-[0.3rem]"
          type="text"
          value={name}
          onChange={(e) => setName(e.target.value)}
          placeholder="Enter your Name"
        />
      </div>
      <div className="flex flex-col py-5 w-[95%] m-auto">
        <label className="mb-[0.5rem] text-base">Email</label>
        <input
          className="py-[0.75rem] px-[1rem] text-xl rounded-[0.3rem]"
          type="email"
          value={email}
          onChange={(e) => setEmail(e.target.value)}
          placeholder="Enter your email"
        />
      </div>
      <div className="flex flex-col py-5 w-[95%] m-auto">
        <label className="mb-[0.5rem] text-base">Phone Number</label>
        <input
          className="py-[0.75rem] px-[1rem] text-xl rounded-[0.3rem]"
          type="number"
          value={phoneNumber}
          onChange={(e) => setPhoneNumber(e.target.value)}
          placeholder="Enter your phone number"
        />
      </div>
      <div className="flex flex-col py-5 w-[95%] m-auto">
        <input
          className="py-[0.75rem] px-[1rem] text-xl rounded-[0.3rem] bg-[#343a40] text-[white]"
          type="button"
          value="Submit"
          placeholder="Enter your phone number"
          onClick={onSubmit}
        />
      </div>
    </form>
  );
};

export default Add;

// src/views/Add.vue
<template>
    <div class='grid justify-center'>
        <div class=' mt-4 grid justify-center items-center  rounded-lg bg-gray-100 mx-8 md:w-[640px] md:mx-32'>
            <div class='  justify-center items-center '>
                <div
                    class=' md:w-[640px]  px-6  py-3 border border-gray-400 bg-gray-200  text-left font-bold text-gray-800 rounded-t-md'>
                    <p>Add Contact</p>
                </div>
    
                <form action="" class='w-[400px] md:w-[640px]  text-left  px-4  pt-4' @submit="onSubmit">
                    <div class='flex flex-col justify-center space-y-2 '>
                        <label class='text-gray-700'>Name</label>
                        <input type="text" class=" border  pl-4 py-3 rounded-md" placeholder='Enter your name...'
                        v-model="name"
                            
                        />
                    </div>
                    <div class='flex flex-col justify-center space-y-2 mt-4'>
                        <label class='text-gray-700'>Email</label>
                        <input type="text" class=" border  pl-4 py-3 rounded-md" placeholder='Enter your email...'
                        v-model="email"
                        />
                    </div>
                    <div class='flex flex-col justify-center space-y-2 mt-4'>
                        <label class='text-gray-700'>phone</label>
                        <input type="text" class=" border  pl-4 py-3 rounded-md" placeholder='Enter your phone...'
                        v-model="phone"
                        />
                    </div>
    
                    <button class='bg-gray-800 text-center w-full text-gray-50 py-2 rounded-md my-4'>Submit</button>
    
    
                </form>
            </div>
    
        </div>
    
    </div>
</template>

<script>
export default {
    name: 'AddTask',
    data() {
        return {
            name: '',
            email: '',
            phone: ''

        }
    },
    methods: {
        onSubmit(e) {
            e.preventDefault()

            const newTask = {
                id: Math.floor(Math.random() * 100000),
                name: this.name,
                email: this.email,
                phone: this.phone
            }
            this.$emit('add-task',newTask)

            this.name = ""
            this.email = ""
            this.phone = ""

        }
    }
}
</script>
