// gamel.ayodele/Module-3/anglarAss/src/app/components/add-info/add-info.component.ts
import {
  Component,
  OnInit,
  Output,
  EventEmitter,
  HostListener,
} from '@angular/core';
import { HomeComponent } from '../home/home.component';
import { Router } from '@angular/router';

import { Info } from '../../Info';
@Component({
  selector: 'app-add-info',
  templateUrl: './add-info.component.html',
  styleUrls: ['./add-info.component.css'],
})
@HostListener('click')
export class AddInfoComponent implements OnInit {
  @Output() onAddInfo: EventEmitter<Info> = new EventEmitter();

  name: string;
  email: string;
  phone: string;
  constructor(private router: Router) {}

  ngOnInit(): void {}
  onSubmit() {
    if (!this.name) {
      alert('please add a Contact');
      return;
    }
    const newInfo: Info = {
      name: this.name,
      email: this.email,
      phone: this.phone,
    };
    this.router.navigate(['/']);
    this.onAddInfo.emit(newInfo);

    this.name = '';
    this.email = '';
    this.phone = '';
  }
}

<form class="container" (ngSubmit)="onSubmit()">
  <div class="card text-dark bg-light">
    <div class="card-header">Add Contact</div>
    <div class="card-body">
      <div class="mb-2">
        <label class="form-label" for="name">Name</label>
        <input
          type="text"
          name="name"
          [(ngModel)]="name"
          placeholder="Add Name"
          class="form-control form-control-lg"
        />
      </div>
      <div class="mb-2">
        <label class="form-label" for="email">Email</label>
        <input
          type="email"
          name="email"
          [(ngModel)]="email"
          placeholder="Add Email"
          class="form-control form-control-lg"
        />
      </div>
      <div class="mb-2">
        <label class="form-label" for="tel">Phone</label>
        <input
          type="tel"
          name="phone"
          [(ngModel)]="phone"
          placeholder="Add Phone"
          class="form-control form-control-lg"
        />
      </div>
      <div class="mb-2">
        <input type="submit" class="form-control" value="Add Contact" />
      </div>
    </div>
  </div>
</form>

// gamel.ayodele/Module-3/vueAss/src/components/AddInfo.vue
<template>
  <form class="container" @submit="onSubmit">
    <div class="card text-dark bg-light">
      <div class="card-header">Add Contact</div>
      <div class="card-body">
        <div class="mb-2">
          <label class="form-label">Name</label>
          <input
            type="text"
            v-model="name"
            placeholder="Add Name"
            class="form-control form-control-lg"
          />
        </div>
        <div class="mb-2">
          <label class="form-label">Email</label>
          <input
            type="email"
            v-model="email"
            placeholder="Add Email"
            class="form-control form-control-lg"
          />
        </div>
        <div class="mb-2">
          <label class="form-label">Phone</label>
          <input
            type="tel"
            v-model="phone"
            placeholder="Add Phone"
            class="form-control form-control-lg"
          />
        </div>

        <div class="mb-2">
          <input type="submit" class="form-control" />
        </div>
      </div>
    </div>
  </form>
</template>

<script>
export default {
  name: "AddInfo",
  data() {
    return {
      name: "",
      email: "",
      phone: "",
    };
  },
  methods: {
    onSubmit(e) {
      e.preventDefault();
      if (!this.name) {
        alert("please add Contact");
        return;
      }
      const newInfo = {
        name: this.name,
        email: this.email,
        phone: this.phone,
      };
      this.$emit("add-info", newInfo);
      this.name = "";
      this.email = "";
      this.phone = "";
      this.$router.push({ path: "/" });
    },
  },
};
</script>

<style scoped>
input[type="submit"] {
  background-color: rgba(59, 58, 58, 0.986);
  color: white;
}
</style>
