// gamel.ayodele/Module-3/reactAss/src/component/AddInfo.jsx
import React from "react";
import { useNavigate } from "react-router-dom";
import { useState, useContext, useEffect } from "react";
import InfoContext from "../context/InfoContext";

const AddInfo = () => {
  const [name, setName] = useState("");
  const [email, setEmail] = useState("");
  const [phone, setPhone] = useState("");
  const { addInfo } = useContext(InfoContext);
  const navigate = useNavigate();

  const onSubmit = (e) => {
    e.preventDefault();
    if (!name) {
      alert("please add a contact");
      return;
    }
    const newInfo = { name, email, phone };

    addInfo(newInfo);

    setName("");
    setEmail("");
    setPhone("");
    navigate("/");
  };

  return (
    <form className="container" onSubmit={onSubmit}>
      <div className="card text-dark bg-light">
        <div className="card-header">Add Contact</div>
        <div className="card-body">
          <div className="mb-2">
            <label className="form-label">Name</label>
            <input
              type="text"
              placeholder="Add Name"
              value={name}
              onChange={(e) => setName(e.target.value)}
              className="form-control form-control-lg"
            />
          </div>
          <div className="mb-2">
            <label className="form-label">Email</label>
            <input
              type="email"
              placeholder="Add Task"
              value={email}
              onChange={(e) => setEmail(e.target.value)}
              className="form-control form-control-lg"
            />
          </div>
          <div className="mb-2">
            <label className="form-label">Phone</label>
            <input
              type="tel"
              placeholder="Add Phone"
              value={phone}
              onChange={(e) => setPhone(e.target.value)}
              className="form-control form-control-lg"
            />
          </div>
          <div className="mb-2">
            <input type="submit" value="Add Contact" className="form-control" />
          </div>
        </div>
      </div>
    </form>
  );
};

export default AddInfo;

// gamel.ayodele/Module-3/vueAss/src/components/AddInfo.vue
<template>
  <form class="container" @submit="onSubmit">
    <div class="card text-dark bg-light">
      <div class="card-header">Add Contact</div>
      <div class="card-body">
        <div class="mb-2">
          <label class="form-label">Name</label>
          <input
            type="text"
            v-model="name"
            placeholder="Add Name"
            class="form-control form-control-lg"
          />
        </div>
        <div class="mb-2">
          <label class="form-label">Email</label>
          <input
            type="email"
            v-model="email"
            placeholder="Add Email"
            class="form-control form-control-lg"
          />
        </div>
        <div class="mb-2">
          <label class="form-label">Phone</label>
          <input
            type="tel"
            v-model="phone"
            placeholder="Add Phone"
            class="form-control form-control-lg"
          />
        </div>

        <div class="mb-2">
          <input type="submit" class="form-control" />
        </div>
      </div>
    </div>
  </form>
</template>

<script>
export default {
  name: "AddInfo",
  data() {
    return {
      name: "",
      email: "",
      phone: "",
    };
  },
  methods: {
    onSubmit(e) {
      e.preventDefault();
      if (!this.name) {
        alert("please add Contact");
        return;
      }
      const newInfo = {
        name: this.name,
        email: this.email,
        phone: this.phone,
      };
      this.$emit("add-info", newInfo);
      this.name = "";
      this.email = "";
      this.phone = "";
      this.$router.push({ path: "/" });
    },
  },
};
</script>

<style scoped>
input[type="submit"] {
  background-color: rgba(59, 58, 58, 0.986);
  color: white;
}
</style>
