// gamel.ayodele/Module-3/reactAss/src/component/Home.jsx
import React from "react";
import ContactList from "./ContactList";
import { useContext } from "react";
import InfoContext from "../context/InfoContext";

function Home({ onDelete }) {
  const { infos } = useContext(InfoContext);

  return (
    <div className="container">
      <div className=" main">
        <h2>Contact Manager</h2>
        <p>This is a portfolio project to showcase knowledge of:</p>
        <ol>
          <li>React Components and Jsx.</li>
          <li>React Router.</li>
          <li>Context api for global state management</li>
          <li>
            Making asynchronous calls to the json placeholder fake rest api
            using "async/await"
          </li>
        </ol>
      </div>

      {infos.map((info) => (
        <ContactList key={info.id} info={info} />
      ))}
    </div>
  );
}

export default Home;

// gamel.ayodele/Module-3/vueAss/src/components/Home.vue
<template>
  <div class="container">
    <div class="main">
      <h2>Contact Manager</h2>
      <p>This is a portfolio project to showcase knowledge of:</p>
      <ol>
        <li>Vue Components</li>
        <li>Vue Router.</li>
        <li>
          Making asynchronous calls to the json placeholder fake rest api using
          "async/await"
        </li>
      </ol>
    </div>
    <div :key="info.id" v-for="info in infos">
      <Info
        @delete-info="$emit('delete-info', info.id)"
        :info="info"
        @edit-info="$emit('edit-info', info)"
      />
    </div>
  </div>
</template>

<script>
import Info from "./Info.vue";
export default {
  name: "Home",
  props: {
    infos: Array,
  },
  components: {
    Info,
  },
};
</script>

<style scoped>
.main {
  display: flex;
  flex-direction: column;
  background-color: #eaeaea;
  padding: 60px;
  margin-bottom: 20px;
}

h2 {
  align-self: center;
}
</style>
