// toluwalase.adeosun/Module3/Vue_Task/vue-contact-manager/src/components/Contacts.vue
<template>
<div :key="contact.id" v-for="contact in contacts">
     <ContactCard :contact="contact"   />

</div>
</template>


<script>
import ContactCard from './ContactCard'
          export default {
    name: 'Contacts',
    props: {
        contacts: Array
    },
    components: {
        ContactCard,
    }
}
</script>

// abdullahi.muritala/module 3/react-contact-man/src/components/Contacts.jsx
import React, { useContext } from 'react';
import { ContactContext } from '../App';
import Contact from './Contact';

const Contacts = () => {
  const { contactList } = useContext(ContactContext);
  return contactList.length
    ? contactList.map((contact) => (
        <Contact
          key={contact.id}
          id={contact.id}
          name={contact.name}
          email={contact.email}
          phone={contact.phone}
        />
      ))
    : '';
};

export default Contacts;
