// abdullahi.muritala/module 3/vue-contact-man/src/components/ProjectDescription.vue
<template>
  <div class="wrapper">
    <h2>Contact Manager</h2>
    <p>This is a portfolio project to showcase knowledge of:</p>
    <ol>
      <li>React Components and JSX</li>
      <li>React Router</li>
      <li>Component state management</li>
      <li>Context api for global state management</li>
      <li>Making asynchronous calls to the JSON placeholder fake RESR API using 'async/await'</li>
      <li>Modular component styling with styled components</li>
    </ol>
  </div>
</template>

<script>
export default {
  name: 'ProjectDescription',
};
</script>

<style scoped>
.wrapper {
  background: #e9ecef;
  padding: 20px 30px;
  margin-bottom: 30px;
}

h2 {
  font-weight: 400;
  text-align: center;
}

ol {
  list-style: lower-roman;
}
</style>

// abdullahi.muritala/module 3/react-contact-man/src/components/ProjectDescription.jsx
import React from 'react';
import { StyledH2, StyledOl, SpecsContainer } from './Home.styles';

const ProjectDescription = () => {
  return (
    <SpecsContainer>
      <StyledH2>Contact Manager</StyledH2>
      <p>This is a portfolio project to showcase knowledge of:</p>
      <StyledOl>
        <li>React Components and JSX</li>
        <li>React Router</li>
        <li>Component state management</li>
        <li>Context api for global state management</li>
        <li>Making asynchronous calls to the JSON placeholder fake RESR API using 'async/await'</li>
        <li>Modular component styling with styled components</li>
      </StyledOl>
    </SpecsContainer>
  );
};

export default ProjectDescription;
