// abdullahi.muritala/module 3/angular-contact-man/src/app/components/editcontact/editcontact.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute, Params, Router } from '@angular/router';
import { Contact } from 'src/app/Contact';
import { ContactService } from 'src/app/services/contact.service';

@Component({
  selector: 'app-editcontact',
  templateUrl: './editcontact.component.html',
  styleUrls: ['./editcontact.component.css'],
})
export class EditcontactComponent implements OnInit {
  myParam!: string;
  contactName: string = '';
  contactEmail: string = '';
  contactPhone: string = '';

  constructor(
    private route: ActivatedRoute,
    private router: Router,
    private contactService: ContactService
  ) {}

  ngOnInit(): void {
    this.route.params.subscribe(
      (params: Params) => (this.myParam = params['id'])
    );

    this.contactService
      .getContactWithId(Number(this.myParam))
      .subscribe((targetContact) => {
        if (targetContact === undefined) return;
        this.contactName = targetContact.name;
        this.contactEmail = targetContact.email;
        this.contactPhone = targetContact.phone;
      });
  }

  onSubmit() {
    const id = Number(this.myParam);

    const updContact: Contact = {
      id,
      name: this.contactName,
      email: this.contactEmail,
      phone: this.contactPhone,
    };

    this.contactService.updateContact(updContact);

    this.router.navigate(['']);

    this.contactName = '';
    this.contactEmail = '';
    this.contactPhone = '';
  }
}

<div class="container">
  <div class="wrapper">
    <h2>Edit Contact</h2>
    <form (ngSubmit)="onSubmit()">
      <div class="form-control">
        <label for="contactName">Name</label>
        <input
          type="text"
          name="contactName"
          id="contactName"
          [(ngModel)]="contactName"
          required
          placeholder="Enter contact's Name"
        />
      </div>
      <div class="form-control">
        <label for="contactEmail">Email</label>
        <input
          type="email"
          [(ngModel)]="contactEmail"
          name="contactEmail"
          id="contactEmail"
          required
          placeholder="Enter contact's Email"
        />
      </div>
      <div class="form-control">
        <label for="contactPhone">Phone</label>
        <input
          type="text"
          [(ngModel)]="contactPhone"
          name="contactPhone"
          id="contactPhone"
          required
          placeholder="Enter contact's Phone"
        />
      </div>
      <input type="submit" value="Submit" />
    </form>
  </div>
</div>

// abdullahi.muritala/module 3/vue-contact-man/src/views/EditContact.vue
<template>
  <div class="container">
    <div class="wrapper">
      <h2>Edit Contact</h2>
      <form @submit="onSubmit">
        <div class="form-control">
          <label for="contactName">Name</label>
          <input
            type="text"
            v-model="targetContact.name"
            name="contactName"
            id="contactName"
            required
            placeholder="Enter contact's Name"
          />
        </div>
        <div class="form-control">
          <label for="contactEmail">Email</label>
          <input
            type="email"
            v-model="targetContact.email"
            name="contactEmail"
            id="contactEmail"
            required
            placeholder="Enter contact's Email"
          />
        </div>
        <div class="form-control">
          <label for="contactPhone">Phone</label>
          <input
            type="text"
            v-model="targetContact.phone"
            name="contactPhone"
            id="contactPhone"
            required
            placeholder="Enter contact's Phone"
          />
        </div>
        <input type="submit" value="Submit" />
      </form>
    </div>
  </div>
</template>

<script>
import { mapActions } from 'vuex';

export default {
  name: 'EditContact',
  methods: {
    ...mapActions(['editContact']),
    onSubmit(event) {
      event.preventDefault();
      const id = Math.floor(Math.random() * 100000);
      const updContact = {
        id,
        name: this.targetContact.name,
        email: this.targetContact.email,
        phone: this.targetContact.phone,
      };
      this.editContact(updContact);
      this.$router.push('/');
    },
  },
  computed: {
    targetContact() {
      return this.$store.getters.getContactById(Number(this.$route.params.id));
    },
  },
};
</script>

<style scoped>
form {
  display: flex;
  flex-direction: column;
  gap: 20px;
}

.form-control {
  display: flex;
  flex-direction: column;
  gap: 5px;
}

input {
  padding: 10px 20px;
  border: 1px solid rgba(0, 0, 0, 0.125);
}

input[type='submit'] {
  padding: 10px 20px;
  background: #343a40;
  color: #ffffff;
}

.wrapper {
  padding: 20px 30px;
  max-width: 720px;
}
</style>
