// Abdulramon Lasisi/Module 3/Task_1_React_Contact_App/contact-manager/src/components/Header.jsx
import React from 'react'
import Title from './Title'
import Button from './Button'
import Links from './Links'

const Header = () => {
  return (
    <header className='bg-gray-700 text-white px-8 py-2 mb-2 sm:flex sm:justify-between sm:items-center'>
      <nav className='flex items-center justify-between'>
        <Title />
        <Button />
      </nav>

      <Links />
    </header>
  )
}

export default Header

// toluwalase.adeosun/Module3/Vue_Task/vue-contact-manager/src/components/Header.vue
<template>
  <div className="header  text-white w-full bg-[#343a40] h-fit ">
    <header className="max-w-[1140px]  m-auto flex justify-between p-2">
      <div className="p-2">
        <h1>Contact Manager</h1>
      </div>
      <Nav />
    </header>
  </div>
</template>

<script>
import Nav from "./Nav.vue";
export default {
  name: "Header",
  components: {
    Nav,
  },
};
</script>

<style>
</style>
